version: "3"
services:
  node-app:
    build: .
    ports:
      - "8000:8080"
    volumes:
      # Mount the current directory into the container
      - .:/app
      # Mount the node_modules directory into the container
      - /app/node_modules
    env_file:
      - .env