version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: local
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=local
    command: npm run dev